name: CustomItems
version: 1.0.4
author: Stefan456789
main: me.Stefan456789.CustomItems
api-version: 1.16
commands:
  drink:
    usage: /drink [Drink]
  disc:
    usage: /disc [Song]
  customItemsState:
    usage: /customItemsState <ON/OFF>